id: P000664
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1PD76232
  title: ཆོས་རྗེ་འཇིགས་མེད་ཕུན་ཚོགས་ཀྱི་རྣམ་ཐར་བསྡུས་པ་དད་པའི་གསོས་སྨན
  author: ''
  volumes:
    af4ee2ebfd1c4a63a9bd4c5ef9185ea1:
      image_group_id: I1PD76235
      title: ''
      volume_number: 1
      total_pages: 98
